export const REGISTER_USER = {
  REQUEST: 'REGISTER_USER_REQUEST',
  SUCCESS: 'REGISTER_USER_SUCCESS',
  FAILURE: 'REGISTER_USER_FAILURE'
};

export const VERIFY_USER_EMAIL = {
  REQUEST: 'VERIFY_USER_EMAIL_REQUEST',
  SUCCESS: 'VERIFY_USER_EMAIL_SUCCESS',
  FAILURE: 'VERIFY_USER_EMAIL_FAILURE'
};

export const LOGIN_USER = {
  REQUEST: 'LOGIN_USER_REQUEST',
  SUCCESS: 'LOGIN_USER_SUCCESS',
  FAILURE: 'LOGIN_USER_FAILURE'
};

export const FETCH_USER_STATUS = {
  REQUEST: 'FETCH_USER_STATUS_REQUEST',
  SUCCESS: 'FETCH_USER_STATUS_SUCCESS',
  FAILURE: 'FETCH_USER_STATUS_FAILURE'
};

export const LOGOUT_USER = 'LOGOUT_USER';
export const PASSWORD_FORGOT = 'PASSWORD_FORGOT';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const CHAT_NEW_CONVERSATION = 'CHAT_NEW_CONVERSATION';

export const UPDATE_PROFILE_BASIC = {
  REQUEST: 'UPDATE_PROFILE_BASIC_REQUEST',
  SUCCESS: 'UPDATE_PROFILE_BASIC_SUCCESS',
  FAILURE: 'UPDATE_PROFILE_BASIC_FAILURE'
};

export const UPDATE_PROFILE_SUMMARY = {
  REQUEST: 'UPDATE_PROFILE_SUMMARY_REQUEST',
  SUCCESS: 'UPDATE_PROFILE_SUMMARY_SUCCESS',
  FAILURE: 'UPDATE_PROFILE_SUMMARY_FAILURE'
};

export const SEND_VERIFICATION_DOCUMENTS = {
  REQUEST: 'SEND_VERIFICATION_DOCUMENTS_REQUEST',
  SUCCESS: 'SEND_VERIFICATION_DOCUMENTS_SUCCESS',
  FAILURE: 'SEND_VERIFICATION_DOCUMENTS_FAILURE'
};

export const ACKNOWLEDGE_VERIFICATION = {
  REQUEST: 'ACKNOWLEDGE_VERIFICATION_REQUEST',
  SUCCESS: 'ACKNOWLEDGE_VERIFICATION_SUCCESS',
  FAILURE: 'ACKNOWLEDGE_VERIFICATION_FAILURE'
};

export const FETCH_COUNTRIES = {
  REQUEST: 'FETCH_COUNTRIES_REQUEST',
  SUCCESS: 'FETCH_COUNTRIES_SUCCESS',
  FAILURE: 'FETCH_COUNTRIES_FAILURE'
};

export const FETCH_CATEGORIES = {
  REQUEST: 'FETCH_CATEGORIES_REQUEST',
  SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FAILURE: 'FETCH_CATEGORIES_FAILURE'
};

export const FETCH_EXPERTISES = {
  REQUEST: 'FETCH_EXPERTISE_REQUEST',
  SUCCESS: 'FETCH_EXPERTISE_SUCCESS',
  FAILURE: 'FETCH_EXPERTISE_FAILURE'
};

export const FETCH_GENRES = {
  REQUEST: 'FETCH_GENRES_REQUEST',
  SUCCESS: 'FETCH_GENRES_SUCCESS',
  FAILURE: 'FETCH_GENRES_FAILURE'
};

export const CLEAR_GENRES = 'CLEAR_GENRES';

export const FETCH_RESOURCES = {
  REQUEST: 'FETCH_RESOURCES_REQUEST',
  SUCCESS: 'FETCH_RESOURCES_SUCCESS',
  FAILURE: 'FETCH_RESOURCES_FAILURE'
};

export const FETCH_RESOURCE_CATEGORIES = {
  REQUEST: 'FETCH_RESOURCE_CATEGORIES_REQUEST',
  SUCCESS: 'FETCH_RESOURCE_CATEGORIES_SUCCESS',
  FAILURE: 'FETCH_RESOURCE_CATEGORIES_FAILURE'
};

export const FETCH_PROFILE = {
  REQUEST: 'FETCH_PROFILE_REQUEST',
  SUCCESS: 'FETCH_PROFILE_SUCCESS',
  FAILURE: 'FETCH_PROFILE_FAILURE'
};

export const FETCH_VENDOR = {
  REQUEST: 'FETCH_VENDOR_REQUEST',
  SUCCESS: 'FETCH_VENDOR_SUCCESS',
  FAILURE: 'FETCH_VENDOR_FAILURE'
};

export const CLEAN_PROFILE_INFO = 'CLEAN_PROFILE_INFO';

export const SEARCH = {
  REQUEST: 'SEARCH_REQUEST',
  SUCCESS: 'SEARCH_SUCCESS',
  FAILURE: 'SEARCH_FAILURE'
};

export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';

export const CREATE_PORTFOLIO = {
  REQUEST: 'CREATE_PORTFOLIO_REQUEST',
  SUCCESS: 'CREATE_PORTFOLIO_SUCCESS',
  FAILURE: 'CREATE_PORTFOLIO_FAILURE'
};

export const FETCH_PORTFOLIO = {
  REQUEST: 'FETCH_PORTFOLIO_REQUEST',
  SUCCESS: 'FETCH_PORTFOLIO_SUCCESS',
  FAILURE: 'FETCH_PORTFOLIO_FAILURE'
};

export const EDIT_PORTFOLIO = {
  REQUEST: 'EDIT_PORTFOLIO_REQUEST',
  SUCCESS: 'EDIT_PORTFOLIO_SUCCESS',
  FAILURE: 'EDIT_PORTFOLIO_FAILURE'
};

export const DELETE_PORTFOLIO = {
  REQUEST: 'DELETE_PORTFOLIO_REQUEST',
  SUCCESS: 'DELETE_PORTFOLIO_SUCCESS',
  FAILURE: 'DELETE_PORTFOLIO_FAILURE'
};

export const FETCH_TEAM = {
  REQUEST: 'FETCH_TEAM_REQUEST',
  SUCCESS: 'FETCH_TEAM_SUCCESS',
  FAILURE: 'FETCH_TEAM_FAILURE'
};

export const REMOVE_TEAM = {
  REQUEST: 'REMOVE_TEAM_REQUEST',
  SUCCESS: 'REMOVE_TEAM_SUCCESS',
  FAILURE: 'REMOVE_TEAM_FAILURE'
};

export const CLEAR_TEAM_LIST = 'CLEAR_TEAM_LIST';

export const FETCH_TOP_VENDORS = {
  REQUEST: 'FETCH_TOP_VENDORS_REQUEST',
  SUCCESS: 'FETCH_TOP_VENDORS_SUCCESS',
  FAILURE: 'FETCH_TOP_VENDORS_FAILURE'
};

export const FETCH_TOP_CUSTOMERS = {
  REQUEST: 'FETCH_TOP_CUSTOMERS_REQUEST',
  SUCCESS: 'FETCH_TOP_CUSTOMERS_SUCCESS',
  FAILURE: 'FETCH_TOP_CUSTOMERS_FAILURE'
};

export const FETCH_CUSTOMERS = {
  REQUEST: 'FETCH_CUSTOMERS_REQUEST',
  SUCCESS: 'FETCH_CUSTOMERS_SUCCESS',
  FAILURE: 'FETCH_CUSTOMERS_FAILURE'
};

export const FETCH_ALL_GENRES = {
  REQUEST: 'FETCH_ALL_GENRES_REQUEST',
  SUCCESS: 'FETCH_ALL_GENRES_SUCCESS',
  FAILURE: 'FETCH_ALL_GENRES_FAILURE'
};

export const FETCH_VENDORS = {
  REQUEST: 'FETCH_VENDORS_REQUEST',
  SUCCESS: 'FETCH_VENDORS_SUCCESS',
  FAILURE: 'FETCH_VENDORS_FAILURE'
};

export const FETCH_PUBLIC_PROFILE = {
  REQUEST: 'FETCH_PUBLIC_PROFILE_REQUEST',
  SUCCESS: 'FETCH_PUBLIC_PROFILE_SUCCESS',
  FAILURE: 'FETCH_PUBLIC_PROFILE_FAILURE'
};

export const FETCH_REVIEW = {
  REQUEST: 'FETCH_REVIEW_REQUEST',
  SUCCESS: 'FETCH_REVIEW_SUCCESS',
  FAILURE: 'FETCH_REVIEW_FAILURE'
};

export const FETCH_CHAT_LIST = {
  REQUEST: 'FETCH_CHAT_LIST_REQUEST',
  SUCCESS: 'FETCH_CHAT_LIST_SUCCESS',
  FAILURE: 'FETCH_CHAT_LIST_FAILURE'
};

export const FETCH_PROJECT_CHAT_LIST = {
  REQUEST: 'FETCH_PROJECT_CHAT_LIST_REQUEST',
  SUCCESS: 'FETCH_PROJECT_CHAT_LIST_SUCCESS',
  FAILURE: 'FETCH_PROJECT_CHAT_LIST_FAILURE'
};

export const FETCH_MESSAGES = {
  REQUEST: 'FETCH_MESSAGES_REQUEST',
  SUCCESS: 'FETCH_MESSAGES_SUCCESS',
  FAILURE: 'FETCH_MESSAGES_FAILURE'
};

export const WS_TYPING = 'WS_TYPING';
export const WS_NEW_MESSAGE = 'WS_NEW_MESSAGE';
export const SET_CHAT_ID = 'SET_CHAT_ID';

export const CREATE_CHAT = {
  REQUEST: 'CREATE_CHAT_REQUEST',
  SUCCESS: 'CREATE_CHAT_SUCCESS',
  FAILURE: 'CREATE_CHAT_FAILURE'
};

export const FETCH_CONTACT_LIST = {
  REQUEST: 'FETCH_CONTACT_LIST_REQUEST',
  SUCCESS: 'FETCH_CONTACT_LIST_SUCCESS',
  FAILURE: 'FETCH_CONTACT_LIST_FAILURE'
};

export const FETCH_PROJECTS_LIST = {
  REQUEST: 'FETCH_PROJECTS_LIST_REQUEST',
  SUCCESS: 'FETCH_PROJECTS_LIST_SUCCESS',
  FAILURE: 'FETCH_PROJECTS_LIST_FAILURE'
};

export const CREATE_PROJECT = {
  REQUEST: 'CREATE_PROJECT_REQUEST',
  SUCCESS: 'CREATE_PROJECT_SUCCESS',
  FAILURE: 'CREATE_PROJECT_FAILURE'
};

export const FETCH_ACC_NOTIFICATIONS = {
  REQUEST: 'FETCH_ACC_NOTIFICATIONS_REQUEST',
  SUCCESS: 'FETCH_ACC_NOTIFICATIONS_SUCCESS',
  FAILURE: 'FETCH_ACC_NOTIFICATIONS_FAILURE'
};

export const FETCH_ACC_INFO = {
  REQUEST: 'FETCH_ACC_INFO_REQUEST',
  SUCCESS: 'FETCH_ACC_INFO_SUCCESS',
  FAILURE: 'FETCH_ACC_INFO_FAILURE'
};

export const UPDATE_ACC_INFO = {
  REQUEST: 'UPDATE_ACC_INFO_REQUEST',
  SUCCESS: 'UPDATE_ACC_INFO_SUCCESS',
  FAILURE: 'UPDATE_ACC_INFO_FAILURE'
};

export const UPDATE_ACC_NOTIFICATIONS = {
  REQUEST: 'UPDATE_ACC_NOTIFICATIONS_REQUEST',
  SUCCESS: 'UPDATE_ACC_NOTIFICATIONS_SUCCESS',
  FAILURE: 'UPDATE_ACC_NOTIFICATIONS_FAILURE'
};

export const FETCH_SAVED_CARDS = {
  REQUEST: 'FETCH_SAVED_CARDS_REQUEST',
  SUCCESS: 'FETCH_SAVED_CARDS_SUCCESS',
  FAILURE: 'FETCH_SAVED_CARDS_FAILURE'
};

export const FETCH_PROJECT = {
  REQUEST: 'FETCH_PROJECT_REQUEST',
  SUCCESS: 'FETCH_PROJECT_SUCCESS',
  FAILURE: 'FETCH_PROJECT_FAILURE'
};

export const FETCH_DELIVERY = {
  REQUEST: 'FETCH_DELIVERY_REQUEST',
  SUCCESS: 'FETCH_DELIVERY_SUCCESS',
  FAILURE: 'FETCH_DELIVERY_FAILURE'
};

export const POST_DELIVERY = {
  REQUEST: 'POST_DELIVERY_REQUEST',
  SUCCESS: 'POST_DELIVERY_SUCCESS',
  FAILURE: 'POST_DELIVERY_FAILURE'
};

export const FETCH_EXTRA_PAYMENTS = {
  REQUEST: 'FETCH_EXTRA_PAYMENTS_REQUEST',
  SUCCESS: 'FETCH_EXTRA_PAYMENTS_SUCCESS',
  FAILURE: 'FETCH_EXTRA_PAYMENTS_FAILURE'
};

export const POST_PROJECT_REVIEW = {
  REQUEST: 'POST_PROJECT_REVIEW_REQUEST',
  SUCCESS: 'POST_PROJECT_REVIEW_SUCCESS',
  FAILURE: 'POST_PROJECT_REVIEW_FAILURE'
};

export const SWITCH_ROLE = 'SWITCH_ROLE';

export const FETCH_ACC_PASS = {
  REQUEST: 'FETCH_ACC_PASS_REQUEST',
  SUCCESS: 'FETCH_ACC_PASS_SUCCESS',
  FAILURE: 'FETCH_ACC_PASS_FAILURE'
};

export const CREATE_PAYMENT = {
  REQUEST: 'CREATE_PAYMENT_REQUEST',
  SUCCESS: 'CREATE_PAYMENT_SUCCESS',
  FAILURE: 'CREATE_PAYMENT_FAILURE'
};

export const ACCEPT_PAYMENT = {
  REQUEST: 'ACCEPT_PAYMENT_REQUEST',
  SUCCESS: 'ACCEPT_PAYMENT_SUCCESS',
  FAILURE: 'ACCEPT_PAYMENT_FAILURE'
};

export const ADD_ADDITIONAL_PAYMENT = 'ADD_ADDITIONAL_PAYMENT';

export const CLEAR_ACC_TYPE = 'CLEAR_ACC_TYPE';

export const FETCH_ACC_TYPE = {
  REQUEST: 'FETCH_ACC_TYPE_REQUEST',
  SUCCESS: 'FETCH_ACC_TYPE_SUCCESS',
  FAILURE: 'FETCH_ACC_TYPE_FAILURE'
};

export const POST_ACC_TYPE = {
  REQUEST: 'POST_ACC_TYPE_REQUEST',
  SUCCESS: 'POST_ACC_TYPE_SUCCESS',
  FAILURE: 'POST_ACC_TYPE_FAILURE'
};

export const UPDATE_ACC_TYPE = {
  REQUEST: 'UPDATE_ACC_TYPE_REQUEST',
  SUCCESS: 'UPDATE_ACC_TYPE_SUCCESS',
  FAILURE: 'UPDATE_ACC_TYPE_FAILURE'
};

export const DEACTIVATE_ACC = {
  REQUEST: 'DEACTIVATE_ACC_REQUEST',
  SUCCESS: 'DEACTIVATE_ACC_SUCCESS',
  FAILURE: 'DEACTIVATE_ACC_FAILURE'
};

export const FETCH_PAYMENT_HISTORY = {
  REQUEST: 'FETCH_PAYMENT_HISTORY_REQUEST',
  SUCCESS: 'FETCH_PAYMENT_HISTORY_SUCCESS',
  FAILURE: 'FETCH_PAYMENT_HISTORY_FAILURE'
};

export const FETCH_PAYMENT_HISTORY_TOTAL = {
  REQUEST: 'FETCH_PAYMENT_HISTORY_TOTAL_REQUEST',
  SUCCESS: 'FETCH_PAYMENT_HISTORY_TOTAL_SUCCESS',
  FAILURE: 'FETCH_PAYMENT_HISTORY_TOTAL_FAILURE'
};

export const FEEDBACK_EMAIL_SENDING = {
  RESET: 'FEEDBACK_EMAIL_SENDING_RESET',
  REQUEST: 'FEEDBACK_EMAIL_SENDING_REQUEST',
  SUCCESS: 'FEEDBACK_EMAIL_SENDING_SUCCESS',
  FAILURE: 'FEEDBACK_EMAIL_SENDING_FAILURE'
};

export const CLEAR_FEEDBACK_EMAIL_SENDING = "CLEAR_FEEDBACK_EMAIL_SENDING";
